name: Build Gradle project

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
        
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew build sonarqube #--info
      #run: ./gradlew sonarqube --no-daemon -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=bestseller-ecom_codecoverage-test -Dsonar.organization=bestseller-ecom
    # - uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    #     directory: ./build/reports/jacoco/
    #     name: codecov-test
    #     verbose: true # optional (default = false)
    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.COVERALLS }}
